export interface Team {
    $key?: string;
    name?: string;
    game?: string;
    description?: string;
    region?: string;
    createdBy?: string;
    createdDate?: string;
    p1Name?: string;
    p1GamerTag?: string;
    p1PSN?:string;
    p1Xbox?:string;
    p1Twitter?: string;
    p1Steam?:string;
    p2Name?: string;
    p2GamerTag?: string;
    p2PSN?:string;
    p2Xbox?:string;
    p2Twitter?: string;
    p2Steam?:string;
    p3Name?: string;
    p3GamerTag?: string;
    p3PSN?:string;
    p3Xbox?:string;
    p3Twitter?: string;
    p3Steam?:string;
    p4Name?: string;
    p4GamerTag?: string;
    p4PSN?:string;
    p4Xbox?:string;
    p4Twitter?: string;
    p4Steam?:string;
    p5Name?: string;
    p5GamerTag?: string;
    p5PSN?:string;
    p5Xbox?:string;
    p5Twitter?: string;
    p5Steam?:string;
    p6Name?: string;
    p6GamerTag?: string;
    p6PSN?:string;
    p6Xbox?:string;
    p6Twitter?: string;
    p6Steam?:string;
}